version: '3'
services:
  db:
    image: wmadata_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WMADATA_DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    container_name: ${WMADATA_DATABASE_ADDRESS}

  liquibase:
    image: wmadata_liquibase
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WMADATA_DATABASE_ADDRESS=${WMADATA_DATABASE_ADDRESS}
      - WMADATA_DATABASE_NAME=${WMADATA_DATABASE_NAME}
      - WMADATA_DB_OWNER_USERNAME=${WMADATA_DB_OWNER_USERNAME}
      - WMADATA_DB_OWNER_PASSWORD=${WMADATA_DB_OWNER_PASSWORD}
      - WMADATA_SCHEMA_NAME=${WMADATA_SCHEMA_NAME}
      - WMADATA_SCHEMA_OWNER_USERNAME=${WMADATA_SCHEMA_OWNER_USERNAME}
      - WMADATA_SCHEMA_OWNER_PASSWORD=${WMADATA_SCHEMA_OWNER_PASSWORD}
      - WMADATA_DB_READ_ONLY_USERNAME=${WMADATA_DB_READ_ONLY_USERNAME}
      - WMADATA_DB_READ_ONLY_PASSWORD=${WMADATA_DB_READ_ONLY_PASSWORD}

    volumes:
      - ./liquibase/changeLogs:/home/java/workspace/wmadata
      - ./liquibase/scripts:/docker-entrypoint-initdb.d
    container_name: wmadata_liquibase

networks:
  wqp:
    external:
      name: ${LOCAL_NETWORK_NAME}
